### PR TITLE
WIP: Chaos Classic Variant

### PR DESCRIPTION
**Pull request by DanielPBak**
This is a WIP because I have not yet found the time to test the variant.

This is an implementation of Chaos diplomacy on the Classic map, based on the existing CustomStart and BuildAnywhere variants.

### CODE REVIEW

**Comment by jmo1121109** [comment]
Hello, haven't you been banned from the website for breaking the rules?

**Comment by DanielPBak** [comment]
That's correct, but I am still looking to contribute.

**Comment by Sleepcap** [comment]
We have the chaos-variant on vDiplomacy (based in the webdip-code) for quite some years now...

**Comment by DanielPBak** [comment]
@jmo1121109 

Would it make sense for me to finish this draft, or would it be better to lift the vDiplomacy version? I wasn't aware of it when I made this.

**Comment by jmo1121109** [comment]
Could you shoot me an email at webdipmod@gmail.com and just address it to jmo and let me know why you're interested in contributing and some thoughts on what you'd like to do?

**Pull request closed without merging**
