### PR TITLE
Better mobile support

### PR DESCRIPTION
**Pull request by Zjcompt**
This is a build I made to better support mobile devices. I was kinda sick and tired of having to zoom in constantly and how most things were very hard to do on a mobile device. This branch adds full mobile support, focused on CSS changes only. There were a few non css files that I had to edit because of inline styling issues.

Everything is working properly in all major browsers:

Tested in:
Edge & IE11
Chrome 49
Safari 10
Firefox 48

No github issue, just want to make the site/project better!

Let me know if there are any concerns or questions!

### CODE REVIEW

**Comment by TimothyJones** [comment]
This is amazing! Thank you so much.

I'll check it out as soon as I can - might not be for a couple of weekends.

**Comment by TimothyJones** [comment]
Also, let me know your webdip user name and I'll make sure you get the proper credit.

Can you tell me what mobile devices/browsers you tested on?

**Comment by Sleepcap** [comment]
With your patch there chat no longer makes a linebreak at the end of a word, but just mid-word...

**Comment by Zjcompt** [comment]
Timothy,

Username (by accident) is: Exectuor

Tested on Android/iOS and Desktop. Specific browsers is on the OP.

--------------------------------

Sleepcap,

I believe I did this change to specifically fix issues like this one:

https://github.com/kestasjk/webDiplomacy/issues/228

What happens is with words that don't have a breaking space, they just go WAYYYYY off the side of the page. It looks a lot worse to me personally. The compromise is that words will break. Do words break on both desktop and mobile? It is more important on mobile because of how much smaller the chat box is.

**Comment by Sleepcap** [comment]
But now it splits words even if there are no really long words wight bevore the last letter.
I'm not sure if it's better or worse...

**Comment by Zjcompt** [comment]
Right, like I said this is the compromise that words will break, I may be able to add a hyphen at the break. I will try to see if I can get a better solution included.

**Comment by Zjcompt** [comment]
@Sleepcap The new commit should fix the issues you were talking about.

**Comment by Sleepcap** [comment]
Works great now.
I will use this on vDiplomacy, so we can see if something important breaks...

**Comment by Sleepcap** [comment]
It's live on vDip. My users already started discussing. There are a few ideas for improvement already.
http://www.vdiplomacy.com/forum.php?viewthread=75175

**Comment by Zjcompt** [comment]
I put another update in so that My Games comes first. I agreed with your users on that. Sometimes you have to scroll really far to get to them.

**Comment by Zjcompt** [comment]
I also noticed that sometimes you use an iframe for the game image. I added a fix so that it doesn't go way off the side of the screen. As for your users that kinda don't like the mobile version you can send them these three links to go to the old non mobile version:

https://ios.gadgethacks.com/how-to/request-desktop-sites-ios-9s-safari-for-ipad-iphone-0163057/
https://www.cnet.com/how-to/how-to-request-desktop-version-of-a-web-site-in-chrome-for-android/
https://support.mozilla.org/en-US/kb/how-do-i-change-desktop-view-firefox-android

**Comment by Sleepcap** [comment]
Thanks, works great so far. The few people complain so far should be able to get the desktop site without any problems. If they really need a setting to "force" the desktop-site I will move the CSS code in an additional file and exclude the file on demand.
Another unrelated question (I have no CSS knowledge, so this is really hard for me): I have a background image for the site. It has a fixed position on all desktop-browsers, but not on iOS. Also maybe it should not load at all on mobile. There is not much too see of it on such small devices.

In the body-CSS I use:
	background:url(../../images/background.jpg) center top repeat-y #dcbea4;
	background-attachment: fixed;

**Comment by TimothyJones** [comment]
Merged and pushed to the site. Thank you so much for this change!

**Comment by TimothyJones** [comment]
@Sleepcap - Do you think you could produce a PR with the opt out fix? I tried to cherry-pick it from the vDip commit history, but it didn't turn out to be straightforward. I'd be very grateful for the contribution!

**Comment by Sleepcap** [comment]
Unfortunately it's really not 100% straightforward, as I have 2 different CSS-styles (webdip and vDip color-scheme), and I moved all my own options to another settings page. Changing this back to the webdip-style needs some time, and I'm currently porting some other variants to the site. So this would take some time.
Basically you just need to put the new mobile-code in a separate CSS-file and only include this in the lib.html if the user has _not_ opt-out in his setting. So if the user has activated the opt-out the mobile-css would not load at all.

**Comment by kestasjk** [comment]
Great work all, and many thanks Zach. Tim are people not okay with changing
their browsers to desktop mode? Mobile browsers almost always have an
option to choose modes for just this sort of reason.

Rgds,
Kestas

**Comment by TimothyJones** [comment]
I think it’s done as a responsive site, rather than a mobile site, so request desktop site doesn’t change it

**Comment by kestasjk** [comment]
Ah I see. What don't people like about it? Is this just aversion to change
or are there things that need to be improved?

**Comment by TimothyJones** [comment]
One person said they use webdip on a desktop in two split screens, both less than 800 pixels wide, triggering the responsive site (one page for orders and one for the map). Probably not a common case. Another said they don’t like the larger font size on mobile. 

Although both of those issues are unlikely to be common, I still think it’s worth having an opt out.

**Comment by kestasjk** [comment]
It looks like the preferred way of having an opt-out for responsive
websites is to put all the @media CSS into a different file, which can then
be included / excluded depending on a user option. Zach / Oliver since you
are more comfortable with the CSS structure could you do this? Once it's in
its own file I can take care of adding a column and user option etc to
allow it to be disabled.

**Comment by Sleepcap** [comment]
Wanted to do a pull-request, but your current branch is not properly maintained at the moment.
in definitions.html the version is set to 143, but the install-files are only up to 142, so I can't test against your latest release.

**Comment by TimothyJones** [comment]
Sorry about that- that’s my fault. There is no 143- you can safely drop that to 142. I’ll make that change in an hour or so. Then you can test with no conflicts.

**Pull request merged**
