### PR TITLE
Update adminActions.php Issue #126

### PR DESCRIPTION
**Pull request by humunuk**
Change description for issue #126

### CODE REVIEW

**Comment by TimothyJones** [comment]
Thanks! Can you make the same change in `adminActionsTD.php` too please, and then I'll accept this change. That way it's one pull request, not two.

**Comment by humunuk** [comment]
I think it's done, let me know if something wrong, learning git(Hub).

**Comment by TimothyJones** [comment]
Great, thanks! I'll have a quick test now, and then accept the change. Normally the description would also include the testing that you've done (ie, in this case verified that the pages still look correct in the browser), but since this is a very easy test, I'll do it myself.

I've just updated the [developer instructions](http://webdiplomacy.net/developers.php) on the website to reflect this. It's only just been updated though, so there's no way you'd have seen this before you made the pull request :)

**Comment by TimothyJones** [comment]
Thanks for the change! Much appreciated!

**Pull request merged**
